# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b911969858a62d7193b88ce1a6e2b158ea58229eaffe361ae804241887593b19055e5eef5d8e0ff7c96a768ca40cb635d686bedab66f42d25efba7096141c2

test:
  secret_key_base: 3283197e3835b2d59f1739ffd361d87097437b5fc8d408355211f221e2ed158262c982a97f523040efef2546b42a906b45128338a03acb6c364a6b3140946809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
